[Git] # This is here just for excludes
extensions = []
comments = []
indicators = [".git"]
exclude = [".git", ".gitignore"]

[Rust]
extensions = ["rs", "rs.in"]
comments = [
  "\\/\\/.*", # Line comment.
  "(?ms)\\/\\*.*?\\*\\/" # Block comment.
]
indicators = ["Cargo.toml", "Cargo.lock"]
exclude = ["target", "Cargo.lock"]

[Toml]
extensions = ["toml"]
comments = [
  "#.*" # Line comment.
]

[Yaml]
extensions = ["yaml", "yml"]
comments = [
  "#.*" # Line comment.
]

[Json]
extensions = ["json"]
comments = []

[Ron]
extensions = ["ron"]
comments = [
  "\\/\\/.*", # Line comment.
  "(?ms)\\/\\*.*?\\*\\/" # Block comment.
]

[Markdown]
extensions = ["md", "mdx", "mdsvex"]
comments = [
  "^<!--\\n(.*(?:\\n.*)*?)\\n-->" # HTML comment.
]

[Wgsl]
extensions = ["wgsl"]
comments = [
  "\\/\\/.*", # Line comment.
  "(?ms)\\/\\*.*?\\*\\/" # Block comment.
]

[Javascript]
extensions = ["js", "jsx", "cjs", "mjs"]
comments = [
  "\\/\\/.*", # Line comment.
  "(?ms)\\/\\*.*?\\*\\/" # Block comment.
]
# TODO: Add more indicators and excludes
indicators = ["node_modules", "package.json", "package-lock.json", "bun.lockb", "pnpm-lock.yaml"]
exclude = ["node_modules", "package-lock.json", "bun.lockb", "pnpm-lock.yaml"]

[Typescript]
extensions = ["ts", "tsx"]
comments = [
  "\\/\\/.*", # Line comment.
  "(?ms)\\/\\*.*?\\*\\/" # Block comment.
]

[Python]
extensions = ["py"]
comments = [
  "#.*" # Line comment.
]
